import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ForttProvider } from '@fortt/react';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ForttProvider
          projectId="cmi4w18p100006m0fzctnhi0b"
          apiBaseUrl="http://localhost:8080"
        >
          {children}
        </ForttProvider>
      </body>
    </html>
  );
}
